name: '1. Скачать модель в датасет'

on:
  workflow_dispatch:

jobs:
  prepare-dataset:
    runs-on: ubuntu-latest
    steps:
      - name: Получить репозиторий
        uses: actions/checkout@v4
      
      - name: Настройка Kaggle API
        env:
          KAGGLE_SECRET_DATA: ${{ secrets.KAGGLE_JSON }}
        run: |
          mkdir -p ~/.kaggle
          printf "%s" "$KAGGLE_SECRET_DATA" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          pip install kaggle
          
      - name: Запуск скачивания на Kaggle
        run: |
          if [ -d "./model_download_job" ]; then
            echo "🚀 Запускаем скачивание модели..."
            kaggle kernels push -p ./model_download_job
            echo "✅ Процесс запущен!"
          else
            echo "❌ Ошибка: папка 'model_download_job' не найдена!"
            exit 1
          fi
